- hosts: localhost
  become: true
- name: Include zsh
  ansible.builtin.import_playbook: sdk/zsh.yml
- name: Include vault
  ansible.builtin.import_playbook: sdk/vault.yml
- name: Include sdkman
  ansible.builtin.import_playbook: sdk/sdkman.yml
- name: Include python
  ansible.builtin.import_playbook: sdk/python.yml
- name: Include nvm
  ansible.builtin.import_playbook: sdk/nvm.yml
- name: Include dbeaver
  ansible.builtin.import_playbook: ide/dbeaver.yml
- name: Include kdenlive
  ansible.builtin.import_playbook: media-editor/kdenlive.yml
- name: Include ide-development
  ansible.builtin.import_playbook: ide/ide-development.yml
- name: Include brave
  ansible.builtin.import_playbook: browser/brave.yml
- name: Draw.io Desktop
  ansible.builtin.import_playbook: util/draw-io.yml
- name: Include Openshift CLI
  ansible.builtin.import_playbook: sdk/openshift-cli.yml
- name: Include chrome
  ansible.builtin.import_playbook: browser/chrome.yml
- name: Install Vscode
  ansible.builtin.import_playbook: ide/vscode.yml
- name: Open Tofu
  ansible.builtin.import_playbook: sdk/open-tofu.yml
- name: Install Vim
  ansible.builtin.import_playbook: sdk/vim.yml
- name: Git secrets
  ansible.builtin.import_playbook: sdk/git-secrets.yml
- name: Veleiro
  ansible.builtin.import_playbook: cli/veleiro.yml
  