- hosts: localhost
  become: true
  tasks:
  - name: Instalando xscreensaver
    apt:
      name: xscreensaver
      state: present
  - name: Instalando xscreensaver bsod
    apt:
      name: xscreensaver-screensaver-bsod
      state: present
  # - name: XScreenSaver | Create Unit file
  #   template: src=xscreensaver.service.j2 dest=/lib/systemd/system/xscreensaver.service mode=644
      # notify:
      #   - reload systemctl
  # - name: SystemCtl reload
  #   shell: systemctl reload
  # - name: XScreenSaver | Start XScreenSaver
    # shell: systemctl --user enable xscreensaver
    