- hosts: localhost
  roles:
    - role: gantsign.intellij
      users:
        - username: "{{ ansible_env.USER }}"
          intellij_disabled_plugins:
            - org.jetbrains.plugins.gradle
            - CVS
            - com.intellij.uiDesigner
            - org.jetbrains.android
            - TestNG-J
            - hg4idea
            - AntSupport
            - DevKit
          intellij_codestyles:
            - name: GoogleStyle
              url: 'https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml'
          intellij_default_codestyle: GoogleStyle
          # intellij_inspection_profiles:
          #   - name: GantSign
          #     url: 'https://raw.githubusercontent.com/gantsign/inspection-profile-intellij/master/GantSign.xml'
          # intellij_default_inspection_profile: GantSign
          intellij_plugins:
            - CheckStyle-IDEA
  tasks:
    - name: Install jq (json editor)
      become: yes
      apt:
        name: jq
        state: present
