- name: Install and configure git-secrets
  hosts: localhost
  become: yes

  tasks:
    - name: Install dependencies for git-secrets (Debian/Ubuntu)
      apt:
        name: 
          - git
          - make
          - wget
        state: present
      when: ansible_os_family == "Debian"

    - name: Install dependencies for git-secrets (RedHat/CentOS)
      yum:
        name:
          - git
          - make
          - wget
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download git-secrets from GitHub
      get_url:
        url: https://github.com/awslabs/git-secrets/archive/refs/heads/master.zip
        dest: /tmp/git-secrets.zip

    - name: Unzip git-secrets
      unarchive:
        src: /tmp/git-secrets.zip
        dest: /tmp/
        remote_src: yes

    - name: Install git-secrets
      command: make install
      args:
        chdir: /tmp/git-secrets-master

    - name: Set up git-secrets in global git template
      shell: |
        git secrets --install ~/.git-templates/git-secrets
        git config --global init.templateDir '~/.git-templates/git-secrets'
        git secrets --register-aws --global

    - name: Apply git-secrets to existing repositories
      shell: |
        find ~ -type d -name ".git" -execdir git secrets --install \;
        find ~ -type d -name ".git" -execdir git secrets --register-aws \;
      args:
        executable: /bin/bash

    - name: Clean up temporary files
      file:
        path: /tmp/git-secrets.zip
        state: absent
      file:
        path: /tmp/git-secrets-master
        state: absent
