---
- name: Install OpenTofu
  hosts: localhost
  become: true
  vars:
    opentofo_version: "1.7.2"  # Especifique a versão desejada ou use "latest" para a versão mais recente
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: 
          - wget
          - unzip
        state: present

    - name: Download OpenTofu
      get_url:
        url: "https://github.com/opentofu/opentofu/releases/download/v{{ opentofo_version }}/tofu_{{ opentofo_version }}_linux_amd64.zip"
        dest: "/tmp/opentofu.zip"

    - name: Unzip OpenTofu
      unarchive:
        src: "/tmp/opentofu.zip"
        dest: "/usr/local/bin"
        remote_src: yes

    - name: Ensure OpenTofu binary is executable
      file:
        path: "/usr/local/bin/tofu"
        mode: '0755'
        state: file

    - name: Verify OpenTofu installation
      command: tofu --version
      register: opentofo_version_output

    - name: Display OpenTofu version
      debug:
        msg: "Installed OpenTofu version: {{ opentofo_version_output.stdout }}"