---
- hosts: localhost
  vars:
    - home: /home/{{ lookup('env', 'USER') }}

  pre_tasks:
    - name: Installing SDKMAn dependencies
      become: true
      apt:
        state: latest
        name:
          - zip
          - unzip
          - curl

  tasks:
    - name: Installing SDK Man
      become: no
      shell: "curl -s 'https://get.sdkman.io' | bash"
      args:
          executable: /bin/zsh

    - name: Adding SDK Man to bash_profile
      lineinfile: path={{ home }}/.bash_profile
        line={{ item }}
        state=present
        create=yes
      with_items:
        - 'source "$HOME/.sdkman/bin/sdkman-init.sh"'
