- hosts: localhost
  name: Playbook para instalar o Vim
  hosts: localhost
  become: yes  # Para garantir que as tarefas sejam executadas com permissões de superusuário
  tasks:
    - name: Atualizar a lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar Vim
      apt:
        name: vim
        state: present